//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.NET.EF6Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.Collections.ObjectModel;
        
    public partial class OrderDetail: INotifyPropertyChanged
    {
        
    			private int _Id;
    			public int Id { 
    				get { return _Id;}
    				set { 
    					if (_Id!=value) {
    						_Id = value;
    						RaisePropertyChanged("Id");
    					}
    				}
               }
        
    			private Nullable<int> _OrderId;
    			public Nullable<int> OrderId { 
    				get { return _OrderId;}
    				set { 
    					if (_OrderId!=value) {
    						_OrderId = value;
    						RaisePropertyChanged("OrderId");
    					}
    				}
               }
        
    			private Nullable<int> _ProductId;
    			public Nullable<int> ProductId { 
    				get { return _ProductId;}
    				set { 
    					if (_ProductId!=value) {
    						_ProductId = value;
    						RaisePropertyChanged("ProductId");
    					}
    				}
               }
        
    			private Nullable<decimal> _UnitPrice;
    			public Nullable<decimal> UnitPrice { 
    				get { return _UnitPrice;}
    				set { 
    					if (_UnitPrice!=value) {
    						_UnitPrice = value;
    						RaisePropertyChanged("UnitPrice");
    					}
    				}
               }
        
    			private Nullable<short> _Quantity;
    			public Nullable<short> Quantity { 
    				get { return _Quantity;}
    				set { 
    					if (_Quantity!=value) {
    						_Quantity = value;
    						RaisePropertyChanged("Quantity");
    					}
    				}
               }
        
    			private Nullable<float> _Discount;
    			public Nullable<float> Discount { 
    				get { return _Discount;}
    				set { 
    					if (_Discount!=value) {
    						_Discount = value;
    						RaisePropertyChanged("Discount");
    					}
    				}
               }
        
    			private byte[] _RowTimeStamp;
    			public byte[] RowTimeStamp { 
    				get { return _RowTimeStamp;}
    				set { 
    					if (_RowTimeStamp!=value) {
    						_RowTimeStamp = value;
    						RaisePropertyChanged("RowTimeStamp");
    					}
    				}
               }
    
        
    			private Order _Order;
    			public virtual Order Order { 
    				get { return _Order;}
    				set { 
    					if (_Order!=value) {
    						_Order = value;
    						RaisePropertyChanged("Order");
    					}
    				}
               }
        
    			private Product _Product;
    			public virtual Product Product { 
    				get { return _Product;}
    				set { 
    					if (_Product!=value) {
    						_Product = value;
    						RaisePropertyChanged("Product");
    					}
    				}
               }
    	public event PropertyChangedEventHandler PropertyChanged;
    	protected virtual void RaisePropertyChanged(string propertyName) {
            	var handler = PropertyChanged;
    			if (handler != null) {
    	            handler(this, new PropertyChangedEventArgs(propertyName));
    			}
        }
    }
}
