//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.NET.EF6Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.Collections.ObjectModel;
        
    public partial class OrderDetail: INotifyPropertyChanged
    {
        
    			private int _ID;
    			public int ID { 
    				get { return _ID;}
    				set { 
    					if (_ID!=value) {
    						_ID = value;
    						RaisePropertyChanged("ID");
    					}
    				}
               }
        
    			private Nullable<int> _OrderID;
    			public Nullable<int> OrderID { 
    				get { return _OrderID;}
    				set { 
    					if (_OrderID!=value) {
    						_OrderID = value;
    						RaisePropertyChanged("OrderID");
    					}
    				}
               }
        
    			private Nullable<int> _ProductID;
    			public Nullable<int> ProductID { 
    				get { return _ProductID;}
    				set { 
    					if (_ProductID!=value) {
    						_ProductID = value;
    						RaisePropertyChanged("ProductID");
    					}
    				}
               }
        
    			private Nullable<decimal> _UnitPrice;
    			public Nullable<decimal> UnitPrice { 
    				get { return _UnitPrice;}
    				set { 
    					if (_UnitPrice!=value) {
    						_UnitPrice = value;
    						RaisePropertyChanged("UnitPrice");
    					}
    				}
               }
        
    			private Nullable<short> _Quantity;
    			public Nullable<short> Quantity { 
    				get { return _Quantity;}
    				set { 
    					if (_Quantity!=value) {
    						_Quantity = value;
    						RaisePropertyChanged("Quantity");
    					}
    				}
               }
        
    			private Nullable<float> _Discount;
    			public Nullable<float> Discount { 
    				get { return _Discount;}
    				set { 
    					if (_Discount!=value) {
    						_Discount = value;
    						RaisePropertyChanged("Discount");
    					}
    				}
               }
        
    			private byte[] _RowTimeStamp;
    			public byte[] RowTimeStamp { 
    				get { return _RowTimeStamp;}
    				set { 
    					if (_RowTimeStamp!=value) {
    						_RowTimeStamp = value;
    						RaisePropertyChanged("RowTimeStamp");
    					}
    				}
               }
    
        
    			private Order _Order;
    			public virtual Order Order { 
    				get { return _Order;}
    				set { 
    					if (_Order!=value) {
    						_Order = value;
    						RaisePropertyChanged("Order");
    					}
    				}
               }
        
    			private Product _Product;
    			public virtual Product Product { 
    				get { return _Product;}
    				set { 
    					if (_Product!=value) {
    						_Product = value;
    						RaisePropertyChanged("Product");
    					}
    				}
               }
    	public event PropertyChangedEventHandler PropertyChanged;
    	protected virtual void RaisePropertyChanged(string propertyName) {
            	var handler = PropertyChanged;
    			if (handler != null) {
    	            handler(this, new PropertyChangedEventArgs(propertyName));
    			}
        }
    }
}
