//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.NET.EF6Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.Collections.ObjectModel;
        
    public partial class Product: INotifyPropertyChanged
    {
        public Product()
        {
            this.OrderDetails = new ObservableCollection<OrderDetail>();
        }
    
        
    			private int _ID;
    			public int ID { 
    				get { return _ID;}
    				set { 
    					if (_ID!=value) {
    						_ID = value;
    						RaisePropertyChanged("ID");
    					}
    				}
               }
        
    			private string _Name;
    			public string Name { 
    				get { return _Name;}
    				set { 
    					if (_Name!=value) {
    						_Name = value;
    						RaisePropertyChanged("Name");
    					}
    				}
               }
        
    			private Nullable<int> _SupplierID;
    			public Nullable<int> SupplierID { 
    				get { return _SupplierID;}
    				set { 
    					if (_SupplierID!=value) {
    						_SupplierID = value;
    						RaisePropertyChanged("SupplierID");
    					}
    				}
               }
        
    			private Nullable<int> _CategoryID;
    			public Nullable<int> CategoryID { 
    				get { return _CategoryID;}
    				set { 
    					if (_CategoryID!=value) {
    						_CategoryID = value;
    						RaisePropertyChanged("CategoryID");
    					}
    				}
               }
        
    			private string _QuantityPerUnit;
    			public string QuantityPerUnit { 
    				get { return _QuantityPerUnit;}
    				set { 
    					if (_QuantityPerUnit!=value) {
    						_QuantityPerUnit = value;
    						RaisePropertyChanged("QuantityPerUnit");
    					}
    				}
               }
        
    			private Nullable<decimal> _UnitPrice;
    			public Nullable<decimal> UnitPrice { 
    				get { return _UnitPrice;}
    				set { 
    					if (_UnitPrice!=value) {
    						_UnitPrice = value;
    						RaisePropertyChanged("UnitPrice");
    					}
    				}
               }
        
    			private Nullable<short> _UnitsInStock;
    			public Nullable<short> UnitsInStock { 
    				get { return _UnitsInStock;}
    				set { 
    					if (_UnitsInStock!=value) {
    						_UnitsInStock = value;
    						RaisePropertyChanged("UnitsInStock");
    					}
    				}
               }
        
    			private Nullable<short> _UnitsOnOrder;
    			public Nullable<short> UnitsOnOrder { 
    				get { return _UnitsOnOrder;}
    				set { 
    					if (_UnitsOnOrder!=value) {
    						_UnitsOnOrder = value;
    						RaisePropertyChanged("UnitsOnOrder");
    					}
    				}
               }
        
    			private Nullable<short> _ReorderLevel;
    			public Nullable<short> ReorderLevel { 
    				get { return _ReorderLevel;}
    				set { 
    					if (_ReorderLevel!=value) {
    						_ReorderLevel = value;
    						RaisePropertyChanged("ReorderLevel");
    					}
    				}
               }
        
    			private Nullable<bool> _Discontinued;
    			public Nullable<bool> Discontinued { 
    				get { return _Discontinued;}
    				set { 
    					if (_Discontinued!=value) {
    						_Discontinued = value;
    						RaisePropertyChanged("Discontinued");
    					}
    				}
               }
        
    			private byte[] _RowTimeStamp;
    			public byte[] RowTimeStamp { 
    				get { return _RowTimeStamp;}
    				set { 
    					if (_RowTimeStamp!=value) {
    						_RowTimeStamp = value;
    						RaisePropertyChanged("RowTimeStamp");
    					}
    				}
               }
    
        
    			private Category _Category;
    			public virtual Category Category { 
    				get { return _Category;}
    				set { 
    					if (_Category!=value) {
    						_Category = value;
    						RaisePropertyChanged("Category");
    					}
    				}
               }
        
    			private ObservableCollection<OrderDetail> _OrderDetails;
    			public virtual ObservableCollection<OrderDetail> OrderDetails { 
    				get { return _OrderDetails;}
    				set { 
    					if (_OrderDetails!=value) {
    						_OrderDetails = value;
    						RaisePropertyChanged("OrderDetails");
    					}
    				}
               }
        
    			private Supplier _Supplier;
    			public virtual Supplier Supplier { 
    				get { return _Supplier;}
    				set { 
    					if (_Supplier!=value) {
    						_Supplier = value;
    						RaisePropertyChanged("Supplier");
    					}
    				}
               }
    	public event PropertyChangedEventHandler PropertyChanged;
    	protected virtual void RaisePropertyChanged(string propertyName) {
            	var handler = PropertyChanged;
    			if (handler != null) {
    	            handler(this, new PropertyChangedEventArgs(propertyName));
    			}
        }
    }
}
