//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.CategoriesFilter {
#if DISABLE_SAMPLE_DATA
#else

    public class Category : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged(nameof(Name));
				}
			}
		}

		private string description = string.Empty;

		public string Description
		{
			get
			{
				return this.description;
			}

			set
			{
				if (this.description != value)
				{
					this.description = value;
					this.OnPropertyChanged(nameof(Description));
				}
			}
		}

		private System.Windows.Media.ImageSource? picture = null;

		public System.Windows.Media.ImageSource? Picture
		{
			get
			{
				return this.picture;
			}

			set
			{
				if (this.picture != value)
				{
					this.picture = value;
					this.OnPropertyChanged(nameof(Picture));
				}
			}
		}
	}
#endif
}
