//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.CategoriesFilter {

#if DISABLE_SAMPLE_DATA
#else

    public class CategoryCollection : System.Collections.ObjectModel.ObservableCollection<Category>
	{ 
	}
#endif
}
